
using Inventory.Domain.Abstraction;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Inventory.Domain.Entities
{
    public class CustomerTransaction : TenantEntity
    {
        [Key]
        public Guid Id { get; set; }

        /*
         * Stable identifier generated by the POS/outbox.
         * TenantId + ClientOperationId must be unique.
         */
        [Required]
        public Guid ClientOperationId { get; set; }

        [Required]
        public Guid CustomerId { get; set; }

        [ForeignKey(nameof(CustomerId))]
        public Customer Customer { get; set; } = null!;

        [Column(TypeName = "decimal(18,2)")]
        public decimal Amount { get; set; }

        [Column(TypeName = "decimal(18,2)")]
        public decimal BalanceBefore { get; set; }

        [Column(TypeName = "decimal(18,2)")]
        public decimal BalanceAfter { get; set; }

        [Required]
        [MaxLength(50)]
        public string Type { get; set; } = string.Empty;

        public Guid? SaleId { get; set; }

        [ForeignKey(nameof(SaleId))]
        public Sale? Sale { get; set; }

        /*
         * Original server cash session selected by the offline POS.
         * It may already be closed when the outbox is uploaded.
         */
        public Guid? CashSessionId { get; set; }

        [ForeignKey(nameof(CashSessionId))]
        public CashSession? CashSession { get; set; }

        public bool IsCash { get; set; }

        [MaxLength(500)]
        public string? Description { get; set; }

        public DateTime TransactionDate { get; set; }
    }
}
