name: ventepilote

services:
  postgres:
    image: postgres:17-alpine
    container_name: ventepilote-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

    networks:
      - ventepilote-network

  api:
    build:
      context: .
      dockerfile: Dockerfile

    image: ventepilote-api:prod
    container_name: ventepilote-api
    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTP_PORTS: 8080
      UseHttpsRedirection: "false"

      ConnectionStrings__DefaultConnection: >-
        Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Timeout=10;SslMode=Disable

      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}
      Jwt__Key: ${JWT_KEY}

    ports:
      - "127.0.0.1:5000:8080"

    volumes:
      - dataprotection:/root/.aspnet/DataProtection-Keys

    networks:
      - ventepilote-network

volumes:
  postgres_data:

  dataprotection:

networks:
  ventepilote-network: