using Inventory.Dto.Sales.Requests;
using System.ComponentModel.DataAnnotations;

namespace Inventory.Dto.Purchases.Requests;

/// <summary>
/// Creates and receives a complete purchase in one atomic operation.
/// </summary>
public sealed class CreateCompletePurchaseRequest
{
    /// <summary>
    /// Unique operation identifier generated by the offline client.
    /// Retrying the same operation must not create another purchase.
    /// </summary>
    [Required]
    public Guid ClientOperationId { get; set; }

    [Required]
    public Guid SupplierId { get; set; }

    public DateTime PurchaseDate { get; set; } =
        DateTime.UtcNow;

    [Required]
    [MinLength(
        1,
        ErrorMessage =
            "At least one purchase line is required.")]
    public List<PurchaseLineItem> Lines { get; set; } =
        new();

    /// <summary>
    /// Optional payment associated with the purchase.
    /// </summary>
    public PaymentInfo? Payment { get; set; }
}

