// <auto-generated />
using System;
using Inventory.LocalDB.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inventory.LocalDB.Migrations
{
    [DbContext(typeof(PosLocalDbContext))]
    [Migration("20260727142449_AddReceiptConfigurations")]
    partial class AddReceiptConfigurations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalCashCorrection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ApprovalNotes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientOperationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CorrectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CorrectedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OriginalLocalCashSessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OriginalServerCashSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientOperationId")
                        .IsUnique();

                    b.HasIndex("OriginalLocalCashSessionId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "OriginalLocalCashSessionId");

                    b.HasIndex("TenantId", "OriginalServerCashSessionId");

                    b.HasIndex("TenantId", "ServerId")
                        .IsUnique()
                        .HasFilter("ServerId IS NOT NULL");

                    b.HasIndex("TenantId", "SyncStatus", "CorrectedAtUtc");

                    b.ToTable("CashCorrections");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalCashMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ClientOperationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LocalCashSessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LocalReferenceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MovementDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerCashSessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerReferenceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientOperationId")
                        .IsUnique();

                    b.HasIndex("LocalCashSessionId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "LocalCashSessionId");

                    b.HasIndex("TenantId", "ServerId")
                        .IsUnique()
                        .HasFilter("ServerId IS NOT NULL");

                    b.HasIndex("TenantId", "SyncStatus");

                    b.HasIndex("TenantId", "Type");

                    b.ToTable("CashMovements");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalCashReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CardSales")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CashSales")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CountedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Difference")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ExpectedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GeneratedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LocalCashSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OtherPayments")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("ServerCashSessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalTransactions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocalCashSessionId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "LocalCashSessionId");

                    b.HasIndex("TenantId", "ServerCashSessionId");

                    b.HasIndex("TenantId", "ServerId")
                        .IsUnique()
                        .HasFilter("ServerId IS NOT NULL");

                    b.HasIndex("TenantId", "Type");

                    b.HasIndex("TenantId", "SyncStatus", "GeneratedAtUtc");

                    b.ToTable("CashReports");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalCashSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientOperationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClosedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ClosingAmountCounted")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ClosingAmountExpected")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ClosingNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Difference")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OpenedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OpenedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OpeningAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OpeningNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientOperationId")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "ServerId")
                        .IsUnique()
                        .HasFilter("ServerId IS NOT NULL");

                    b.HasIndex("TenantId", "SessionNumber")
                        .IsUnique();

                    b.HasIndex("TenantId", "Status");

                    b.HasIndex("TenantId", "SyncStatus");

                    b.ToTable("CashSessions");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalCustomer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name");

                    b.HasIndex("ServerId");

                    b.HasIndex("SyncStatus");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "IsDeleted");

                    b.HasIndex("TenantId", "ServerId")
                        .IsUnique()
                        .HasFilter("ServerId IS NOT NULL");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalCustomerTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BalanceAfter")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BalanceBefore")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ClientOperationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomerLocalId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CustomerServerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCash")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LocalCashSessionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SaleLocalId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SaleServerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerCashSessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TransactionDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("UploadRequired")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerLocalId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "ClientOperationId")
                        .IsUnique();

                    b.HasIndex("TenantId", "ServerId")
                        .IsUnique()
                        .HasFilter("ServerId IS NOT NULL");

                    b.HasIndex("TenantId", "SyncStatus");

                    b.HasIndex("TenantId", "CustomerLocalId", "TransactionDateUtc");

                    b.HasIndex("TenantId", "Origin", "SaleLocalId");

                    b.ToTable("CustomerTransactions");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalDamage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DamageDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DamageNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DeletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EstimatedValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductLocalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProductServerId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerStatus")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ValidatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductLocalId");

                    b.HasIndex("TenantId", "DamageNumber")
                        .IsUnique();

                    b.HasIndex("TenantId", "LocalStatus");

                    b.HasIndex("TenantId", "ProductLocalId");

                    b.HasIndex("TenantId", "ServerId")
                        .IsUnique()
                        .HasFilter("ServerId IS NOT NULL");

                    b.ToTable("Damages");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalPackComponent", b =>
                {
                    b.Property<Guid>("ProductCatalogId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ComponentCatalogId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.HasKey("ProductCatalogId", "ComponentCatalogId");

                    b.HasIndex("ComponentCatalogId");

                    b.ToTable("PackComponents");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CardLastFourDigits")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRefunded")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LocalSaleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PaidAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RefundedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerSaleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionRef")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocalSaleId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "LocalSaleId");

                    b.HasIndex("TenantId", "Method");

                    b.HasIndex("TenantId", "ServerId")
                        .IsUnique()
                        .HasFilter("ServerId IS NOT NULL");

                    b.HasIndex("TenantId", "ServerSaleId");

                    b.HasIndex("TenantId", "SyncStatus");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CatalogProductId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeletedLocally")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPack")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTracked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LocalStockQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("MaxStockLevel")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("MinStockLevel")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PurchasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalePrice2")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalePrice3")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ServerModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sku")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UnitProductLocalId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UnitProductServerId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitsPerPack")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("VatRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("Barcode");

                    b.HasIndex("CatalogProductId");

                    b.HasIndex("Name");

                    b.HasIndex("SyncStatus");

                    b.HasIndex("TenantId");

                    b.HasIndex("UnitProductLocalId");

                    b.HasIndex("UnitProductServerId");

                    b.HasIndex("TenantId", "CatalogProductId")
                        .IsUnique()
                        .HasFilter("CatalogProductId IS NOT NULL AND IsDeletedLocally = 0");

                    b.HasIndex("TenantId", "IsDeletedLocally");

                    b.HasIndex("TenantId", "ServerId")
                        .IsUnique()
                        .HasFilter("ServerId IS NOT NULL");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalProductCatalog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPack")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SellingMode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ServerCreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ServerModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Barcode");

                    b.HasIndex("CategoryId");

                    b.HasIndex("InternalCode");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name");

                    b.ToTable("ProductCatalogs");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("LastSyncedAtUtc");

                    b.HasIndex("Name");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalPurchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientOperationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeliveryDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpectedDeliveryDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPurchaseNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaymentDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaymentDueDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PurchaseDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerPurchaseNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierInvoiceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SupplierLocalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SupplierServerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmountExclVat")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmountInclVat")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalVatAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClientOperationId")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "LocalPurchaseNumber")
                        .IsUnique();

                    b.HasIndex("TenantId", "ServerId")
                        .IsUnique()
                        .HasFilter("ServerId IS NOT NULL");

                    b.HasIndex("TenantId", "ServerPurchaseNumber");

                    b.HasIndex("TenantId", "Status");

                    b.HasIndex("TenantId", "SupplierLocalId");

                    b.HasIndex("TenantId", "SupplierServerId");

                    b.HasIndex("TenantId", "SyncStatus", "PurchaseDateUtc");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalPurchaseLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("LocalPurchaseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductBarcode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductLocalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProductServerId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("QuantityOrdered")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("QuantityReceived")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPurchasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VatRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("LocalPurchaseId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "LocalPurchaseId");

                    b.HasIndex("TenantId", "ProductBarcode");

                    b.HasIndex("TenantId", "ProductLocalId");

                    b.HasIndex("TenantId", "ProductServerId");

                    b.ToTable("PurchaseLines");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalPurchasePayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LocalPurchaseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PaymentDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerPurchaseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionRef")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocalPurchaseId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "LocalPurchaseId");

                    b.HasIndex("TenantId", "Method");

                    b.HasIndex("TenantId", "ServerId")
                        .IsUnique()
                        .HasFilter("ServerId IS NOT NULL");

                    b.HasIndex("TenantId", "ServerPurchaseId");

                    b.HasIndex("TenantId", "SyncStatus", "PaymentDateUtc");

                    b.ToTable("PurchasePayments");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LocalSaleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerSaleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "InvoiceNumber");

                    b.HasIndex("TenantId", "LocalSaleId")
                        .IsUnique();

                    b.ToTable("Receipts", (string)null);
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalReceiptPrintLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("CopyNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LocalReceiptId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrintType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PrintedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PrintedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasSuccessful")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "LocalReceiptId", "PrintedAtUtc");

                    b.ToTable("ReceiptPrintLogs", (string)null);
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalReturn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CashSessionServerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientOperationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CustomerLocalId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CustomerServerId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LocalCashSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalReturnNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LocalSaleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalLocalInvoiceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalServerInvoiceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RefundMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReturnDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerReturnNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerSaleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClientOperationId")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "CustomerLocalId");

                    b.HasIndex("TenantId", "LocalCashSessionId");

                    b.HasIndex("TenantId", "LocalReturnNumber")
                        .IsUnique();

                    b.HasIndex("TenantId", "LocalSaleId");

                    b.HasIndex("TenantId", "RefundMethod");

                    b.HasIndex("TenantId", "ServerId")
                        .IsUnique()
                        .HasFilter("ServerId IS NOT NULL");

                    b.HasIndex("TenantId", "ServerReturnNumber");

                    b.HasIndex("TenantId", "ServerSaleId");

                    b.HasIndex("TenantId", "SyncStatus", "ReturnDateUtc");

                    b.ToTable("Returns");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalReturnLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPack")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LocalReturnId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LocalSaleLineId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductBarcode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductLocalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProductServerId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RestockItem")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ServerSaleLineId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitCostPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UnitProductLocalId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UnitProductServerId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("UnitsPerPack")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("VatRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("LocalReturnId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "LocalReturnId");

                    b.HasIndex("TenantId", "LocalSaleLineId");

                    b.HasIndex("TenantId", "ProductBarcode");

                    b.HasIndex("TenantId", "ProductLocalId");

                    b.HasIndex("TenantId", "ProductServerId");

                    b.HasIndex("TenantId", "UnitProductLocalId");

                    b.HasIndex("TenantId", "UnitProductServerId");

                    b.ToTable("ReturnLines");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalSale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CashSessionServerId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ChangeAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ClientOperationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CustomerLocalId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CustomerServerId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LocalCashSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalInvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PaidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiptBarcodeValue")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SaleDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerInvoiceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SubtotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VatAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CashSessionServerId");

                    b.HasIndex("ClientOperationId")
                        .IsUnique();

                    b.HasIndex("CustomerLocalId");

                    b.HasIndex("CustomerServerId");

                    b.HasIndex("LocalCashSessionId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "LocalInvoiceNumber")
                        .IsUnique();

                    b.HasIndex("TenantId", "ReceiptBarcodeValue")
                        .IsUnique()
                        .HasFilter("\"ReceiptBarcodeValue\" IS NOT NULL AND trim(\"ReceiptBarcodeValue\") <> ''");

                    b.HasIndex("TenantId", "ServerId")
                        .IsUnique()
                        .HasFilter("\"ServerId\" IS NOT NULL");

                    b.HasIndex("TenantId", "SyncStatus", "SaleDateUtc");

                    b.ToTable("Sales", (string)null);
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalSaleLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DiscountPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsPack")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LocalSaleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductBarcode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductLocalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProductServerId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitCostPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UnitProductLocalId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UnitProductServerId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("UnitsPerPack")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("VatRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("LocalSaleId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "LocalSaleId");

                    b.HasIndex("TenantId", "ProductLocalId");

                    b.HasIndex("TenantId", "ProductServerId");

                    b.HasIndex("TenantId", "UnitProductServerId");

                    b.ToTable("SaleLines");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalStock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductBarcode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductLocalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProductServerId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("ReservedQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<Guid?>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ProductLocalId")
                        .IsUnique();

                    b.HasIndex("TenantId", "ProductServerId");

                    b.HasIndex("TenantId", "ServerId")
                        .IsUnique()
                        .HasFilter("ServerId IS NOT NULL");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalStockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientOperationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LocalReferenceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MovementDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductBarcode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductLocalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductServerId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("QuantityAfter")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("QuantityBefore")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("QuantityChange")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerReferenceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClientOperationId")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "LocalReferenceId");

                    b.HasIndex("TenantId", "ProductLocalId");

                    b.HasIndex("TenantId", "ProductServerId");

                    b.HasIndex("TenantId", "ServerId")
                        .IsUnique()
                        .HasFilter("ServerId IS NOT NULL");

                    b.HasIndex("TenantId", "ServerReferenceId");

                    b.HasIndex("TenantId", "SyncStatus");

                    b.HasIndex("TenantId", "Type");

                    b.ToTable("StockMovements");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalStoreProfile", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("EUR");

                    b.Property<string>("CurrencySymbol")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("€");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LegalName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("fr-BE");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mobile")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReceiptConfigurationUpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiptCurrencyCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("EUR");

                    b.Property<string>("ReceiptDefaultCashierName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiptExtraAddressLine")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiptFooter")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiptHeader")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiptHeaderTagLine")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ReceiptLogoBytes")
                        .HasColumnType("BLOB");

                    b.Property<string>("ReceiptLogoContentType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiptLogoFileName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiptSocialLine")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TradeName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("TenantId");

                    b.ToTable("StoreProfiles", (string)null);
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalSupplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("BankAccount")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentTermsDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("Phone");

                    b.HasIndex("SyncStatus");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "IsDeleted");

                    b.HasIndex("TenantId", "Name");

                    b.HasIndex("TenantId", "ServerId")
                        .IsUnique()
                        .HasFilter("ServerId IS NOT NULL");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalUserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTrialActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastOfflineAccessAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastOnlineLoginAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OfflinePasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("OfflinePasswordIterations")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OfflinePasswordSalt")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TokenExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TrialEndDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("IsActive");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.SyncQueueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ClientOperationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastAttemptAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LocalEntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerEntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientOperationId")
                        .IsUnique();

                    b.HasIndex("EntityName");

                    b.HasIndex("LocalEntityId");

                    b.HasIndex("Status");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "EntityName", "LocalEntityId");

                    b.HasIndex("TenantId", "Status", "CreatedAtUtc");

                    b.ToTable("SyncQueueItems");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.SyncTableStateLocal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContinuationToken")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("InitialSyncCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastServerChangeAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSuccessfulSyncAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Syncmode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "EntityName")
                        .IsUnique();

                    b.HasIndex("TenantId", "InitialSyncCompleted");

                    b.ToTable("SyncTableStates");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalCashCorrection", b =>
                {
                    b.HasOne("Inventory.LocalDB.Models.LocalCashSession", "OriginalLocalCashSession")
                        .WithMany()
                        .HasForeignKey("OriginalLocalCashSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OriginalLocalCashSession");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalCashMovement", b =>
                {
                    b.HasOne("Inventory.LocalDB.Models.LocalCashSession", "LocalCashSession")
                        .WithMany("CashMovements")
                        .HasForeignKey("LocalCashSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocalCashSession");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalCashReport", b =>
                {
                    b.HasOne("Inventory.LocalDB.Models.LocalCashSession", "LocalCashSession")
                        .WithMany()
                        .HasForeignKey("LocalCashSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocalCashSession");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalCustomerTransaction", b =>
                {
                    b.HasOne("Inventory.LocalDB.Models.LocalCustomer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerLocalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalDamage", b =>
                {
                    b.HasOne("Inventory.LocalDB.Models.LocalProduct", "Product")
                        .WithMany()
                        .HasForeignKey("ProductLocalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalPackComponent", b =>
                {
                    b.HasOne("Inventory.LocalDB.Models.LocalProductCatalog", "ProductCatalog")
                        .WithMany("PackComponents")
                        .HasForeignKey("ProductCatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductCatalog");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalPayment", b =>
                {
                    b.HasOne("Inventory.LocalDB.Models.LocalSale", "LocalSale")
                        .WithMany("Payments")
                        .HasForeignKey("LocalSaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocalSale");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalProduct", b =>
                {
                    b.HasOne("Inventory.LocalDB.Models.LocalProductCatalog", null)
                        .WithMany()
                        .HasForeignKey("CatalogProductId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalPurchaseLine", b =>
                {
                    b.HasOne("Inventory.LocalDB.Models.LocalPurchase", "LocalPurchase")
                        .WithMany("Lines")
                        .HasForeignKey("LocalPurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocalPurchase");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalPurchasePayment", b =>
                {
                    b.HasOne("Inventory.LocalDB.Models.LocalPurchase", "LocalPurchase")
                        .WithMany("Payments")
                        .HasForeignKey("LocalPurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocalPurchase");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalReturnLine", b =>
                {
                    b.HasOne("Inventory.LocalDB.Models.LocalReturn", "LocalReturn")
                        .WithMany("Lines")
                        .HasForeignKey("LocalReturnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocalReturn");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalSale", b =>
                {
                    b.HasOne("Inventory.LocalDB.Models.LocalCashSession", "LocalCashSession")
                        .WithMany("Sales")
                        .HasForeignKey("LocalCashSessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LocalCashSession");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalSaleLine", b =>
                {
                    b.HasOne("Inventory.LocalDB.Models.LocalSale", "LocalSale")
                        .WithMany("Lines")
                        .HasForeignKey("LocalSaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocalSale");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalCashSession", b =>
                {
                    b.Navigation("CashMovements");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalProductCatalog", b =>
                {
                    b.Navigation("PackComponents");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalPurchase", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalReturn", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalSale", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
