// <auto-generated />
using System;
using Inventory.LocalDB.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inventory.LocalDB.Migrations
{
    [DbContext(typeof(PosLocalDbContext))]
    [Migration("20260715151938_addTenantToLocal")]
    partial class addTenantToLocal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalCashCorrection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ApprovalNotes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientOperationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CorrectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CorrectedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OriginalLocalCashSessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OriginalServerCashSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientOperationId")
                        .IsUnique();

                    b.HasIndex("CorrectedAtUtc");

                    b.HasIndex("OriginalLocalCashSessionId");

                    b.HasIndex("OriginalServerCashSessionId");

                    b.HasIndex("ServerId");

                    b.HasIndex("SyncStatus");

                    b.ToTable("CashCorrections");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalCashMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ClientOperationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LocalCashSessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LocalReferenceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MovementDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerCashSessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerReferenceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientOperationId")
                        .IsUnique();

                    b.HasIndex("LocalCashSessionId");

                    b.HasIndex("ServerId");

                    b.HasIndex("SyncStatus");

                    b.HasIndex("Type");

                    b.ToTable("CashMovements");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalCashReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CardSales")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CashSales")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CountedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Difference")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ExpectedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GeneratedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LocalCashSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OtherPayments")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("ServerCashSessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalTransactions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedAtUtc");

                    b.HasIndex("LocalCashSessionId");

                    b.HasIndex("ServerCashSessionId");

                    b.HasIndex("ServerId");

                    b.HasIndex("SyncStatus");

                    b.HasIndex("Type");

                    b.ToTable("CashReports");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalCashSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientOperationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClosedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ClosingAmountCounted")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ClosingAmountExpected")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ClosingNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Difference")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OpenedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OpenedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OpeningAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OpeningNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientOperationId")
                        .IsUnique();

                    b.HasIndex("ServerId");

                    b.HasIndex("SessionNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("SyncStatus");

                    b.ToTable("CashSessions");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalCustomer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name");

                    b.HasIndex("ServerId");

                    b.HasIndex("SyncStatus");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalPackComponent", b =>
                {
                    b.Property<Guid>("ProductCatalogId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ComponentCatalogId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.HasKey("ProductCatalogId", "ComponentCatalogId");

                    b.HasIndex("ComponentCatalogId");

                    b.ToTable("PackComponents");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CardLastFourDigits")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRefunded")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LocalSaleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PaidAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RefundedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerSaleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionRef")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocalSaleId");

                    b.HasIndex("Method");

                    b.HasIndex("ServerId");

                    b.HasIndex("ServerSaleId");

                    b.HasIndex("SyncStatus");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CatalogProductId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeletedLocally")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPack")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTracked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LocalStockQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("MaxStockLevel")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("MinStockLevel")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PurchasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalePrice2")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalePrice3")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ServerModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sku")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UnitProductLocalId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UnitProductServerId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitsPerPack")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("VatRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("Barcode");

                    b.HasIndex("Name");

                    b.HasIndex("SyncStatus");

                    b.HasIndex("TenantId");

                    b.HasIndex("UnitProductLocalId");

                    b.HasIndex("UnitProductServerId");

                    b.HasIndex("TenantId", "CatalogProductId");

                    b.HasIndex("TenantId", "IsDeletedLocally");

                    b.HasIndex("TenantId", "ServerId")
                        .IsUnique()
                        .HasFilter("ServerId IS NOT NULL");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalProductCatalog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPack")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SellingMode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ServerCreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ServerModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Barcode");

                    b.HasIndex("CategoryId");

                    b.HasIndex("InternalCode");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name");

                    b.ToTable("ProductCatalogs");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("LastSyncedAtUtc");

                    b.HasIndex("Name");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalPurchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientOperationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeliveryDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpectedDeliveryDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPurchaseNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaymentDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaymentDueDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PurchaseDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerPurchaseNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierInvoiceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SupplierLocalId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SupplierServerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmountExclVat")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmountInclVat")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalVatAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClientOperationId")
                        .IsUnique();

                    b.HasIndex("LocalPurchaseNumber")
                        .IsUnique();

                    b.HasIndex("PurchaseDateUtc");

                    b.HasIndex("ServerId");

                    b.HasIndex("ServerPurchaseNumber");

                    b.HasIndex("Status");

                    b.HasIndex("SupplierLocalId");

                    b.HasIndex("SupplierServerId");

                    b.HasIndex("SyncStatus");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalPurchaseLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LocalPurchaseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductBarcode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductLocalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProductServerId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("QuantityOrdered")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("QuantityReceived")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("UnitPurchasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VatRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("LocalPurchaseId");

                    b.HasIndex("ProductBarcode");

                    b.HasIndex("ProductLocalId");

                    b.HasIndex("ProductServerId");

                    b.ToTable("PurchaseLines");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalPurchasePayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LocalPurchaseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PaymentDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerPurchaseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionRef")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocalPurchaseId");

                    b.HasIndex("Method");

                    b.HasIndex("PaymentDateUtc");

                    b.HasIndex("ServerId");

                    b.HasIndex("ServerPurchaseId");

                    b.HasIndex("SyncStatus");

                    b.ToTable("PurchasePayments");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalReturn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientOperationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalReturnNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LocalSaleId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RefundMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReturnDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerReturnNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerSaleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClientOperationId")
                        .IsUnique();

                    b.HasIndex("LocalReturnNumber")
                        .IsUnique();

                    b.HasIndex("LocalSaleId");

                    b.HasIndex("RefundMethod");

                    b.HasIndex("ReturnDateUtc");

                    b.HasIndex("ServerId");

                    b.HasIndex("ServerReturnNumber");

                    b.HasIndex("ServerSaleId");

                    b.HasIndex("SyncStatus");

                    b.ToTable("Returns");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalReturnLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LocalReturnId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductBarcode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductLocalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProductServerId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RestockItem")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VatRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("LocalReturnId");

                    b.HasIndex("ProductBarcode");

                    b.HasIndex("ProductLocalId");

                    b.HasIndex("ProductServerId");

                    b.ToTable("ReturnLines");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalSale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CashSessionServerId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ChangeAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ClientOperationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CustomerLocalId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CustomerServerId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LocalCashSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalInvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PaidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SaleDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerInvoiceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SubtotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VatAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CashSessionServerId");

                    b.HasIndex("ClientOperationId")
                        .IsUnique();

                    b.HasIndex("CustomerLocalId");

                    b.HasIndex("CustomerServerId");

                    b.HasIndex("LocalCashSessionId");

                    b.HasIndex("LocalInvoiceNumber")
                        .IsUnique();

                    b.HasIndex("SaleDateUtc");

                    b.HasIndex("ServerId");

                    b.HasIndex("SyncStatus");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalSaleLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DiscountPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsPack")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LocalSaleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductBarcode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductLocalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProductServerId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("UnitCostPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UnitProductLocalId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UnitProductServerId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("UnitsPerPack")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("VatRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("LocalSaleId");

                    b.HasIndex("ProductLocalId");

                    b.HasIndex("ProductServerId");

                    b.HasIndex("UnitProductServerId");

                    b.ToTable("SaleLines");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalStock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductBarcode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductLocalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductServerId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("ReservedQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<Guid?>("ServerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductBarcode");

                    b.HasIndex("ProductLocalId")
                        .IsUnique();

                    b.HasIndex("ProductServerId")
                        .IsUnique();

                    b.HasIndex("ServerId");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalStockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientOperationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LocalReferenceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MovementDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductBarcode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductLocalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductServerId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("QuantityAfter")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("QuantityBefore")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("QuantityChange")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerReferenceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClientOperationId")
                        .IsUnique();

                    b.HasIndex("LocalReferenceId");

                    b.HasIndex("ProductLocalId");

                    b.HasIndex("ProductServerId");

                    b.HasIndex("ServerId");

                    b.HasIndex("ServerReferenceId");

                    b.HasIndex("SyncStatus");

                    b.HasIndex("Type");

                    b.ToTable("StockMovements");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalSupplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("BankAccount")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentTermsDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name");

                    b.HasIndex("Phone");

                    b.HasIndex("ServerId");

                    b.HasIndex("SyncStatus");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalUserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTrialActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastOfflineAccessAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastOnlineLoginAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OfflinePasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("OfflinePasswordIterations")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OfflinePasswordSalt")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TokenExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TrialEndDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("IsActive");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.SyncQueueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ClientOperationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastAttemptAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LocalEntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerEntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientOperationId")
                        .IsUnique();

                    b.HasIndex("EntityName");

                    b.HasIndex("LocalEntityId");

                    b.HasIndex("Status");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "EntityName", "LocalEntityId");

                    b.HasIndex("TenantId", "Status", "CreatedAtUtc");

                    b.ToTable("SyncQueueItems");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.SyncTableStateLocal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSyncErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("LocalVersion")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ServerVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Syncmode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntityName")
                        .IsUnique();

                    b.ToTable("SyncTableStates");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalCashCorrection", b =>
                {
                    b.HasOne("Inventory.LocalDB.Models.LocalCashSession", "OriginalLocalCashSession")
                        .WithMany()
                        .HasForeignKey("OriginalLocalCashSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OriginalLocalCashSession");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalCashMovement", b =>
                {
                    b.HasOne("Inventory.LocalDB.Models.LocalCashSession", "LocalCashSession")
                        .WithMany("CashMovements")
                        .HasForeignKey("LocalCashSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocalCashSession");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalCashReport", b =>
                {
                    b.HasOne("Inventory.LocalDB.Models.LocalCashSession", "LocalCashSession")
                        .WithMany()
                        .HasForeignKey("LocalCashSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocalCashSession");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalPackComponent", b =>
                {
                    b.HasOne("Inventory.LocalDB.Models.LocalProductCatalog", "ProductCatalog")
                        .WithMany("PackComponents")
                        .HasForeignKey("ProductCatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductCatalog");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalPayment", b =>
                {
                    b.HasOne("Inventory.LocalDB.Models.LocalSale", "LocalSale")
                        .WithMany("Payments")
                        .HasForeignKey("LocalSaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocalSale");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalPurchaseLine", b =>
                {
                    b.HasOne("Inventory.LocalDB.Models.LocalPurchase", "LocalPurchase")
                        .WithMany("Lines")
                        .HasForeignKey("LocalPurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocalPurchase");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalPurchasePayment", b =>
                {
                    b.HasOne("Inventory.LocalDB.Models.LocalPurchase", "LocalPurchase")
                        .WithMany("Payments")
                        .HasForeignKey("LocalPurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocalPurchase");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalReturnLine", b =>
                {
                    b.HasOne("Inventory.LocalDB.Models.LocalReturn", "LocalReturn")
                        .WithMany("Lines")
                        .HasForeignKey("LocalReturnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocalReturn");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalSale", b =>
                {
                    b.HasOne("Inventory.LocalDB.Models.LocalCashSession", "LocalCashSession")
                        .WithMany("Sales")
                        .HasForeignKey("LocalCashSessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LocalCashSession");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalSaleLine", b =>
                {
                    b.HasOne("Inventory.LocalDB.Models.LocalSale", "LocalSale")
                        .WithMany("Lines")
                        .HasForeignKey("LocalSaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocalSale");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalCashSession", b =>
                {
                    b.Navigation("CashMovements");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalProductCatalog", b =>
                {
                    b.Navigation("PackComponents");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalPurchase", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalReturn", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Inventory.LocalDB.Models.LocalSale", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
