<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0" />
    <PackageReference Include="QuestPDF" Version="2026.7.1" />
    <PackageReference Include="Refit" Version="9.0.2" />
    <PackageReference Include="SkiaSharp" Version="4.150.1" />
    <PackageReference Include="ZXing.Net" Version="0.16.11" />
    <PackageReference Include="ZXing.Net.Bindings.SkiaSharp" Version="0.16.22" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\dotNetApiProBoilerplate.Dto\Inventory.Dto.csproj" />
  </ItemGroup>

</Project>
